### ISSUE TITLE
Non-Weather

### ISSUE THREAD

**Issue by aareben** [MatthiPi/MMM-DefaultWeatherAnimated#2]
Is there anyway you could do this for weather forecast and currentwather, because when I tried to change over to weather, the forecast part every stops loading.

**Comment by MatthiPi** [comment]
Hi

I had the same problem. I had to change something in my config file, but I can not remember what.
Mine now looks like that and it works:

		{
		module: "weather",
		position: "upper_third",
			config: {
				// See 'Configuration options' for more information.
				type: 'current',
				weatherEndpoint: '/weather',
				units: 'metric',
				apiKey: 'xxxx',
				locationID: 2778067
			}
		},
		
		{
		module: "weather",
		position: "upper_third",
			config: {
				// See 'Configuration options' for more information.
				weatherEndpoint: '/forecast',
				type: 'forecast',
				units: 'metric',
				fade: false,
				apiKey: 'xxxxx',
				locationID: 2778067
			}
		},

**Comment by aareben** [comment]
Thanks, it now works and looks great.
