### ISSUE TITLE
I could'nt make it nothing change

### ISSUE THREAD

**Issue by emrahaslan** [MatthiPi/MMM-DefaultWeatherAnimated#3]
I copy all files into modules/default/weather directory as you mnetioned.
(not into weather forecast directory)

My config js file 

`	{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "İstanbul",
				roundTemp: true,
				degreeLabel: true,
				showPeriod: false,
				onlyTemp: true,
				locationID: "xx", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "xx",
				
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "5 DAYİ",
			config: {
				location: "İstanbul",
				locationID: "xx", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "xxx",
				colored:true,
		     	roundTemp:true,
		    	maxNumberOfDays:14,
			    initialLoadDelay: '1000',
			  
			}
		},`

But the result was original. what should i do?

![image](https://user-images.githubusercontent.com/54321532/92612311-6c228400-f2c2-11ea-8a6c-abb0755abc93.png)

![image](https://user-images.githubusercontent.com/54321532/92612435-8b211600-f2c2-11ea-823c-dccaa740a425.png)

**Comment by MatthiPi** [comment]
Hi
Everything looks correct.
Did you restart the MM App after you did the changes?
Have overwritten the original files with the ones I provided?
Did you empty the browser cache?

This is my config:

	{
	module: "weather",
	position: "upper_third",
		config: {
			// See 'Configuration options' for more information.
			type: 'current',
			weatherEndpoint: '/weather',
			units: 'metric',
			apiKey: 'xxxx',
			locationID: 2778067
		}
	},
	
	{
	module: "weather",
	position: "upper_third",
		config: {
			// See 'Configuration options' for more information.
			weatherEndpoint: '/forecast',
			type: 'forecast',
			units: 'metric',
			fade: false,
			apiKey: 'xxxxx',
			locationID: 2778067
		}
	},

I hope it helps.

**Comment by emrahaslan** [comment]
Hi, After restart It's works thanks

**Comment by emrahaslan** [comment]
Thanks for quick help
