### ISSUE TITLE
Icon matches issue

### ISSUE THREAD

**Issue by emrahaslan** [MatthiPi/MMM-DefaultWeatherAnimated#4]
I tried to compare weather icons with my previos design but I'm confused. My previus icons show "sunny" icon for next days, but this theme shows cloudy. I wonder which icon is true. I will be happy if you explain this, maybe I missed something.

(both of are same api)
![image](https://user-images.githubusercontent.com/54321532/92712240-0d144c00-f362-11ea-89f7-37901f8db384.png)

**Comment by MatthiPi** [comment]
all weather conditions are shown here: https://openweathermap.org/weather-conditions
but I did not have svg icons for every condition.. so some will use the same icon

it would be best to compare it to the icons shown in openweather forcast:
![image](https://user-images.githubusercontent.com/69600805/92716032-945fc080-f35e-11ea-8822-cd0655af10cd.png)
this is Istambul and it seems like my icons are a better match

**Comment by emrahaslan** [comment]
It seems your icons are correct :) thanks
