### ISSUE TITLE
Try to send notification to compliments

### ISSUE THREAD

**Issue by emrahaslan** [MatthiPi/MMM-DefaultWeatherAnimated#5]
Hello again, love that module, but unable to find node_helper.js inside of default/weather  directory.

I would like to send notification to client side in order to listen and put appropriate text for current weather.

My compliment module have this 

	notificationReceived: function(notification, payload, sender) {
		if (notification === "CURRENTWEATHER_DATA") {
			console.log("251", payload.data);
			this.setCurrentWeatherType(payload.data);
		}

But I dont get how to send data from your module.

Pls help me

**Comment by MatthiPi** [comment]
sorry but I did not develop the weather module.
So I can not help you there

**Comment by emrahaslan** [comment]
But the replaced one (old module) current  weather is disabled. It has notifaction.
