### ISSUE TITLE
pb with the city name

### ISSUE THREAD

**Issue by tchouky85** [MatthiPi/MMM-DefaultWeatherAnimated#6]
>hello, i used your app it works great except i can't put the name of my city instead i have: graz

Do you have a solution ?
here is my code:

{
         module: "weather",
         position: "top_bar",
	     config: {
		    // See 'Configuration options' for more information.
		    type: 'current',
			weatherEndpoint: '/weather',
		    units: 'metric',
                    location : 'Bussy-lettrée',
		    apiKey: 'xx',
	            locationID: 2995603
	     }
      },
	  {
         module: "weather",
         position: "top_bar",
	     config: {
		    // See 'Configuration options' for more information.
		    type: 'forecast',
			weatherEndpoint: '/forecast',
			fade: false,
			units: 'metric',
		    apiKey: 'xx',
			locationID: 2995603
	     }
      },

**Comment by MatthiPi** [comment]
uuuups I hardcoded it.
You can change it current.njk in line 42.

	<div class="weather-today">
		<div class="large light">
			<div class="city">
				Graz
			</div>
			
			<div class="today-weather-icon">
