### ISSUE TITLE
Unable to send notification

### ISSUE THREAD

**Issue by emrahaslan** [MatthiPi/MMM-DefaultWeatherAnimated#7]
Hi, I floowed your steps and thats ok, its working.

But unable to figure out how to send notification to current weather objects into my compliment_modules.

(where should I write , this code in this module ?) when I try in provider.js, console says "sender should be module"

this.sendNotification("CURRENTWEATHER_DATA", {foo: "bar"});

MY COMPLIMENT_PLUS Modul   compliment_plus.js

notificationReceived: function(notification, payload, sender) {
		if (notification === "CURRENTWEATHER_DATA") {
			console.log("251", payload.data);
			this.setCurrentWeatherType(payload.data);
		}
	},

**Comment by emrahaslan** [comment]
I need your help, please do nut close issue until I accept this.

**Comment by MatthiPi** [comment]
sorry but I did not develop the weather module or the current weather module
So I said I can not help you there.

**Comment by emrahaslan** [comment]
Hello,

As you know we are disabling "currentweather" module in config.js file according this.

{
			module: "weather",   //change to weather
			position: "top_right",
				config: {
					// See 'Configuration options' for more information.
					type: 'current',
					weatherEndpoint: '/weather',
					units: 'metric',
					apiKey: 'X',
					locationID: Y
				}
		},

So  I cannot send notification to my compliment site.
